require: rubocop-rspec
AllCops:
  NewCops: enable
  Include:
    - '**/*.rb'
    - '*.gemspec'
    - '**/Rakefile'
    - '**/Gemfile'
    - 'bin/rika'
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectOutput:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
